tasks:
  - name: Temporalite
    init: go install github.com/DataDog/temporalite/cmd/temporalite@latest
    command: temporalite start --namespace default --ephemeral
  - name: Remote Codec Server
    command: go run ./codecserver -origin $(gp url 8233)
  - name: Shell
    init: go install github.com/temporalio/tctl/cmd/tctl@v1.16.1
    command: |
      gp await-port 8234 && echo "Remote Codec Server Endpoint: $(gp url 8234)"

ports:
  - port: 7233 # temporal server
    onOpen: ignore
  - port: 8233 # temporal web
    onOpen: open-browser
  - port: 8234 # remote codec server
    onOpen: ignore
    visibility: public
    